import { useEffect, useMemo, useState } from 'react'
import { db } from './db/database'
import { assetTypes, type Asset, type AssetListItem, type AssetType, typeName, type Tag } from './types/asset'
import { processImages } from './services/imageService'
import { downloadBackup, exportBackup, restoreBackup } from './services/backupService'
import { copyText } from './services/clipboardService'

type Tab = 'home' | 'browse' | 'favorites' | 'mine'
type Input = Omit<Asset, 'id' | 'nameNormalized' | 'createdAt' | 'updatedAt' | 'imageIds'> & { tags: string[] }
type SortMode = 'recent' | 'oldest' | 'name' | 'favorite'
interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>
}

export default function App() {
  const [tab, setTab] = useState<Tab>('home'), [assets, setAssets] = useState<AssetListItem[]>([]), [query, setQuery] = useState(''), [type, setType] = useState<AssetType | 'all'>('all'), [sort, setSort] = useState<SortMode>('recent')
  const [detail, setDetail] = useState<AssetListItem | null>(null), [editing, setEditing] = useState<AssetListItem | null | 'new'>(null), [notice, setNotice] = useState(''), [tagsOpen,setTagsOpen]=useState(false), [storageOpen,setStorageOpen]=useState(false), [updateReady,setUpdateReady]=useState(false)
  const [installPrompt,setInstallPrompt]=useState<BeforeInstallPromptEvent|null>(null), [installOpen,setInstallOpen]=useState(false), [installed,setInstalled]=useState(()=>window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator & {standalone?:boolean}).standalone)), [online,setOnline]=useState(navigator.onLine)
  const refresh = async () => setAssets(await db.listAssets())
  useEffect(() => { void refresh().catch(() => setNotice('无法读取本地收藏，请使用系统浏览器打开')) }, [])
  useEffect(() => { const handler=()=>setUpdateReady(true); window.addEventListener('shining-update-ready',handler); return()=>window.removeEventListener('shining-update-ready',handler) }, [])
  useEffect(() => { const prompt=(event:Event)=>{event.preventDefault();setInstallPrompt(event as BeforeInstallPromptEvent)}, done=()=>{setInstalled(true);setInstallPrompt(null);setInstallOpen(false);setNotice('已安装到设备 ♡');setTimeout(()=>setNotice(''),1800)}, connected=()=>setOnline(true), disconnected=()=>setOnline(false); window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('appinstalled',done);window.addEventListener('online',connected);window.addEventListener('offline',disconnected);return()=>{window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('appinstalled',done);window.removeEventListener('online',connected);window.removeEventListener('offline',disconnected)} }, [])
  useEffect(() => { const url=new URL(location.href);if(url.searchParams.get('action')==='new'){setEditing('new');url.searchParams.delete('action');history.replaceState(null,'',url)} }, [])
  const visible = useMemo(() => assets.filter(a => (type === 'all' || a.type === type) && (tab !== 'favorites' || a.favorite) && (!query || [a.name, a.sourceAuthor, a.sourcePlatform, a.note, ...a.tags.map(t => t.name)].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a,b)=>sort==='oldest'?a.createdAt-b.createdAt:sort==='name'?a.name.localeCompare(b.name,'zh-CN'):sort==='favorite'?(Number(b.favorite)-Number(a.favorite)||b.createdAt-a.createdAt):b.createdAt-a.createdAt), [assets, type, tab, query, sort])
  const notify = (text: string) => { setNotice(text); setTimeout(() => setNotice(''), 1800) }
  const install = async () => { if(installed){notify('已经安装到设备');return}if(!installPrompt){setInstallOpen(true);return}try{await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==='accepted')setInstallPrompt(null);else notify('已取消安装')}catch{setInstallOpen(true)} }
  const copy = async (code: string) => { if (await copyText(code)) notify('已复制'); else notify('浏览器禁止复制，请长按素材码手动复制') }
  const save = async (input: Input, old?: AssetListItem, files: File[] = []) => { try { const saved = await db.saveAsset(input, old); if (files.length) await db.addImages(saved.id, await processImages(saved.id, files)); await refresh(); setEditing(null); notify(old ? '已保存修改' : '收藏成功 ♡') } catch { notify('保存失败，请检查设备存储空间后重试') } }
  const remove = async (asset: AssetListItem) => { if (!confirm(`确定删除「${asset.name}」吗？`)) return; await db.deleteAsset(asset.id); await refresh(); setDetail(null); notify('已删除') }
  const go = (next: Tab) => { setTab(next); setQuery(''); setType('all') }
  return <main className="app-shell"><section className="phone">{!online&&<div className="offline-banner">当前处于离线模式，本地收藏仍可使用</div>}
    <div className="page"><header className="topbar"><div><p className="eyebrow">MY LITTLE ARCHIVE</p><h1>{tab === 'mine' ? '我的收藏库' : tab === 'favorites' ? '特别收藏 ♥' : tab === 'browse' ? '分类' : '闪亮收藏 ♡'}</h1></div><button className="avatar">L</button></header>
    {tab === 'home' && <><label className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索名字、标签、作者……" /></label>{!installed&&<InstallCard ready={Boolean(installPrompt)} install={()=>void install()}/>}<section><div className="section-heading"><h2>我的分类</h2><button onClick={() => go('browse')}>查看全部</button></div><div className="category-row">{assetTypes.map(t => <button className={`category-card ${t.tint}`} key={t.id} onClick={() => { setType(t.id); setTab('browse') }}><i>{t.icon}</i><strong>{t.name}</strong><small>{assets.filter(a => a.type === t.id).length}</small></button>)}</div></section><section className="recent"><div className="section-heading"><div><h2>最近收藏</h2><p>为下一次闪亮登场准备</p></div></div><Grid assets={visible.slice().sort((a,b) => b.createdAt-a.createdAt)} detail={setDetail} copy={copy}/></section></>}
    {tab === 'browse' && <><div className="filters"><button className={type === 'all' ? 'active' : ''} onClick={() => setType('all')}>全部</button>{assetTypes.map(t => <button key={t.id} className={type === t.id ? 'active' : ''} onClick={() => setType(t.id)}>{t.name}</button>)}</div><div className="filter-row"><span>共 {visible.length} 个素材</span><select value={sort} onChange={e=>setSort(e.target.value as SortMode)}><option value="recent">最近添加</option><option value="oldest">最早添加</option><option value="name">名称排序</option><option value="favorite">收藏优先</option></select></div><Grid assets={visible} detail={setDetail} copy={copy}/></>}
    {tab === 'favorites' && <><p className="fave-summary">已经收藏了 <b>{visible.length}</b> 个心动瞬间</p><Grid assets={visible} detail={setDetail} copy={copy}/></>}
    {tab === 'mine' && <><Mine assets={assets} tags={()=>setTagsOpen(true)} install={()=>void install()} installed={installed} backup={async()=>{try{downloadBackup(await exportBackup());notify('备份已开始下载')}catch{notify('备份失败，请稍后重试')}}} restore={async(file)=>{if(!confirm('恢复会替换当前全部收藏。建议先导出当前备份，确定继续吗？'))return;try{await restoreBackup(file);await refresh();notify('恢复完成 ♡')}catch{notify('恢复失败，请检查备份文件')}}}/><button className="storage-entry" onClick={()=>setStorageOpen(true)}>存储空间 ›</button></>}</div><button className="add-button" aria-label="新增素材" onClick={() => setEditing('new')}>＋</button><Nav tab={tab} go={go}/></section>
    {detail && <Detail asset={detail} close={() => setDetail(null)} copy={copy} edit={() => setEditing(detail)} remove={() => void remove(detail)} updateImages={async(imageIds,coverImageId)=>{await db.updateImageOrder(detail,imageIds,coverImageId);await refresh();setDetail({...detail,imageIds,coverImageId})}} deleteImage={async(imageId)=>{if(confirm('删除这张图片吗？')){await db.deleteImage(detail.id,imageId);await refresh();setDetail({...detail,imageIds:detail.imageIds.filter(id=>id!==imageId),coverImageId:detail.coverImageId===imageId?detail.imageIds.find(id=>id!==imageId):detail.coverImageId})}}} toggle={async () => { await db.setFavorite(detail, !detail.favorite); await refresh(); setDetail({...detail,favorite:!detail.favorite}) }}/>} {tagsOpen&&<TagSheet assets={assets} close={()=>setTagsOpen(false)} filter={tag=>{setQuery(tag.name);setTab('browse');setTagsOpen(false)}}/>} {storageOpen&&<StorageSheet close={()=>setStorageOpen(false)} done={()=>{void refresh();notify('清理完成')}}/>} {installOpen&&<InstallSheet close={()=>setInstallOpen(false)}/>} {editing && <Editor asset={editing === 'new' ? undefined : editing} close={() => setEditing(null)} save={save}/>} {updateReady&&<div className="update-toast">发现新版本 ♡<button onClick={()=>location.reload()}>更新</button></div>} {notice && <div className="toast">{notice}</div>}</main>
}
function Thumb({id}:{id?:string}) { const [url,setUrl]=useState<string>(); useEffect(()=>{let u='';void db.getImage(id??'').then(x=>{if(x){u=URL.createObjectURL(x.thumbnailBlob);setUrl(u)}});return()=>{if(u)URL.revokeObjectURL(u)}},[id]); return url?<img className="stored-thumb" src={url} alt=""/>:<><span className="silhouette"/><span className="sparkle">✦</span></> }
function Grid({assets,detail,copy}:{assets:AssetListItem[];detail:(a:AssetListItem)=>void;copy:(c:string)=>void}) { if (!assets.length) return <div className="empty"><span>♡</span><h2>这里还没有闪亮收藏呢</h2><p>点右下角 ＋，收藏第一个素材吧</p></div>; return <div className="asset-grid">{assets.map((a,i) => <article className="asset-card" key={a.id}><button className={`asset-image portrait-${['rose','silver','red','gold','lemon','pink'][i%6]}`} onClick={() => detail(a)}><Thumb id={a.coverImageId}/></button><div className="asset-copy"><div className="asset-title"><button onClick={() => detail(a)}>{a.name}</button>{a.favorite&&<span>♥</span>}</div><div className="chips">{a.tags.slice(0,2).map(t=><em key={t.id}>#{t.name}</em>)}</div><div className="card-actions"><small>{typeName(a.type)}</small><button onClick={() => void copy(a.code)}>复制</button></div></div></article>)}</div> }
function FullImage({id}:{id?:string}) { const [url,setUrl]=useState<string>(); useEffect(()=>{let u='';void db.getImage(id??'').then(x=>{if(x){u=URL.createObjectURL(x.fullBlob);setUrl(u)}});return()=>{if(u)URL.revokeObjectURL(u)}},[id]);return url?<img className="stored-full" src={url} alt="素材图片"/>:<span className="silhouette"/> }
function ImageStrip({asset,select}:{asset:AssetListItem;select:(id:string)=>void}) { const [urls,setUrls]=useState<string[]>([]); useEffect(()=>{let current:string[]=[];void Promise.all(asset.imageIds.map(id=>db.getImage(id))).then(images=>{current=images.flatMap(image=>image?[URL.createObjectURL(image.thumbnailBlob)]:[]);setUrls(current)});return()=>current.forEach(URL.revokeObjectURL)},[asset.imageIds]); return urls.length>1?<div className="image-strip">{urls.map((url,index)=><button key={url} onClick={()=>select(asset.imageIds[index])}><img src={url} alt={`图片 ${index+1}`}/></button>)}</div>:null }
function Detail({asset,close,copy,edit,remove,toggle,updateImages,deleteImage}:{asset:AssetListItem;close:()=>void;copy:(c:string)=>void;edit:()=>void;remove:()=>void;toggle:()=>void;updateImages:(ids:string[],cover?:string)=>void;deleteImage:(id:string)=>void}) { const [active,setActive]=useState(asset.coverImageId); useEffect(()=>{const handle=(event:KeyboardEvent)=>event.key==='Escape'&&close();window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[close]); const move=(step:number)=>{const i=asset.imageIds.indexOf(active??'');const j=i+step;if(i<0||j<0||j>=asset.imageIds.length)return;const ids=[...asset.imageIds];[ids[i],ids[j]]=[ids[j],ids[i]];updateImages(ids)}; return <div className="overlay" onClick={close}><div className="detail-sheet" onClick={event=>event.stopPropagation()}><div className="detail-image portrait-rose"><button className="close" aria-label="返回首页" onClick={close}>‹</button><FullImage id={active}/></div><div className="detail-body"><ImageStrip asset={asset} select={setActive}/>{active&&<div className="image-actions"><button onClick={()=>updateImages(asset.imageIds,active)}>设为封面</button><button onClick={()=>move(-1)}>← 前移</button><button onClick={()=>move(1)}>后移 →</button><button onClick={()=>deleteImage(active)}>删除图片</button></div>}<div className="detail-title"><div><p>{typeName(asset.type)}</p><h2>{asset.name}</h2></div><button className="heart" onClick={toggle}>{asset.favorite?'♥':'♡'}</button></div><div className="chips">{asset.tags.map(t=><em key={t.id}>#{t.name}</em>)}</div><div className="code-box"><p>{asset.code}</p><button onClick={()=>void copy(asset.code)}>复制</button></div><dl><div><dt>来源</dt><dd>{asset.sourcePlatform||'未记录'}</dd></div><div><dt>作者</dt><dd>{asset.sourceAuthor||'未记录'}</dd></div><div><dt>添加日期</dt><dd>{new Date(asset.createdAt).toLocaleDateString('zh-CN')}</dd></div></dl>{asset.note&&<p className="note">{asset.note}</p>}<div className="detail-actions"><button onClick={edit}>编辑</button><button className="danger" onClick={remove}>删除</button></div></div></div></div> }
function Editor({asset,close,save}:{asset?:AssetListItem;close:()=>void;save:(i:Input,o?:AssetListItem,files?:File[])=>Promise<void>}) { const [type,setType]=useState<AssetType>(asset?.type??'face'),[files,setFiles]=useState<File[]>([]); const previews=files.map(file=>URL.createObjectURL(file)); useEffect(()=>()=>previews.forEach(URL.revokeObjectURL),[files]); return <div className="overlay"><form className="add-sheet" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({type,name:String(f.get('name')),code:String(f.get('code')),favorite:f.get('favorite')==='on',sourcePlatform:String(f.get('platform')),sourceAuthor:String(f.get('author')),sourceUrl:'',note:String(f.get('note')),coverImageId:asset?.coverImageId,tags:String(f.get('tags')).split(/[，,\s]+/).filter(Boolean)},asset,files)}}><header><button type="button" onClick={close}>取消</button><h2>{asset?'编辑素材':'新增素材'}</h2><button>保存</button></header><label className="upload-placeholder">{previews[0]?<><img src={previews[0]} alt="所选封面"/><b>已选择 {files.length} 张图片</b><small>再次点击可重新选择</small></>:<><span>＋</span><b>添加图片</b><small>最多 9 张，首张默认封面</small></>}<input name="images" type="file" accept="image/*" multiple hidden onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,9))}/></label><div className="form-group"><span>素材类型</span><div className="type-pills">{assetTypes.map(t=><button type="button" key={t.id} className={type===t.id?'active':''} onClick={()=>setType(t.id)}>{t.name}</button>)}</div></div><label className="form-group"><span>名称 <b>必填</b></span><input name="name" defaultValue={asset?.name} required/></label><label className="form-group"><span>素材码 <b>必填</b></span><textarea name="code" defaultValue={asset?.code} required/></label><label className="form-group"><span>标签</span><input name="tags" defaultValue={asset?.tags.map(t=>t.name).join('，')} placeholder="甜妹，清冷，中式"/></label><label className="favorite-row"><input name="favorite" type="checkbox" defaultChecked={asset?.favorite}/> <span>设为特别收藏 ♥</span></label><label className="form-group"><span>来源平台</span><select name="platform" defaultValue={asset?.sourcePlatform??'小红书'}><option>小红书</option><option>B站</option><option>微博</option><option>游戏社区</option><option>好友</option><option>其他</option></select></label><label className="form-group"><span>作者</span><input name="author" defaultValue={asset?.sourceAuthor}/></label><label className="form-group"><span>备注</span><textarea name="note" defaultValue={asset?.note}/></label><button className="save-wide">{asset?'保存修改':'保存到收藏 ♡'}</button></form></div> }
function Mine({assets,tags:openTags,install,installed,backup,restore}:{assets:AssetListItem[];tags:()=>void;install:()=>void;installed:boolean;backup:()=>void;restore:(file:File)=>void}) { const tags=new Set(assets.flatMap(a=>a.tags.map(t=>t.id))).size, [storage,setStorage]=useState('检测中'); useEffect(()=>{void(async()=>{if(!navigator.storage?.persisted){setStorage('浏览器不支持');return}const enabled=await navigator.storage.persisted();if(!enabled)await navigator.storage.persist?.();setStorage((await navigator.storage.persisted())?'已启用':'未启用')})()},[]);return <><section className="stat-card"><div><b>{assets.length}</b><span>全部素材</span></div><div><b>{assets.reduce((n,a)=>n+a.imageIds.length,0)}</b><span>图片</span></div><div><b>{tags}</b><span>标签</span></div></section><section className="backup-card"><div className="backup-icon">⌁</div><div><h2>记得备份呀</h2><p>备份只保存在你的下载位置</p></div><button onClick={backup}>导出</button></section><section className="storage-status"><span>存储保护</span><b>{storage}</b><p>可降低浏览器在空间不足时回收本地数据的概率，仍建议定期备份。</p></section><section className="settings"><h2>应用与数据</h2><button onClick={install}>安装到手机<span>{installed?'已安装 ✓':'›'}</span></button><button onClick={backup}>完整备份<span>›</span></button><label className="restore-button">导入恢复<input type="file" accept=".zip,application/zip" onChange={e=>{const f=e.target.files?.[0];if(f)restore(f)}}/><span>›</span></label><button onClick={openTags}>标签管理<span>›</span></button>{['存储空间（即将推出）','隐私说明'].map(x=><button key={x}>{x}<span>›</span></button>)}</section><p className="compatibility-note">若微信内置浏览器无法下载备份或安装应用，请使用系统浏览器打开。</p></> }
function InstallCard({ready,install}:{ready:boolean;install:()=>void}) { return <section className="install-card"><img src={`${import.meta.env.BASE_URL}icon.svg`} alt=""/><div><h2>安装「闪亮收藏」</h2><p>{ready?'已准备好，安装后可从桌面直接打开':'添加到主屏幕，像普通 App 一样使用'}</p></div><button onClick={install}>安装</button></section> }
function InstallSheet({close}:{close:()=>void}) { const ua=navigator.userAgent,isIOS=/iPhone|iPad|iPod/i.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),isInApp=/MicroMessenger|QQ\//i.test(ua);return <div className="overlay" onClick={close}><div className="detail-sheet install-sheet" onClick={event=>event.stopPropagation()}><header><button onClick={close}>‹ 返回</button><h2>安装到手机</h2></header><img src={`${import.meta.env.BASE_URL}icon.svg`} alt="闪亮收藏图标"/><h3>{isInApp?'请先在系统浏览器打开':isIOS?'使用 Safari 添加到主屏幕':'从浏览器菜单安装'}</h3>{isInApp?<ol><li>点击右上角菜单</li><li>选择“在浏览器打开”</li><li>再按照浏览器提示安装</li></ol>:isIOS?<ol><li>使用 Safari 打开本站</li><li>点击底部的“分享”按钮</li><li>选择“添加到主屏幕”，再点“添加”</li></ol>:<ol><li>点击浏览器右上角菜单</li><li>选择“安装应用”或“添加到主屏幕”</li><li>确认安装即可</li></ol>}<p>收藏图片和素材码保存在当前设备，请继续定期导出备份。</p><button className="save-wide" onClick={close}>我知道了</button></div></div> }
function StorageSheet({close,done}:{close:()=>void;done:()=>void}) { const [summary,setSummary]=useState<{assetCount:number;imageCount:number;imageBytes:number;orphanCount:number}>(); useEffect(()=>{void db.storageSummary().then(setSummary)},[]); const clean=async()=>{if(!summary?.orphanCount||!confirm(`确定清理 ${summary.orphanCount} 张无引用图片吗？`))return;await db.clearOrphanImages();done();close()}; return <div className="overlay" onClick={close}><div className="detail-sheet tag-sheet" onClick={e=>e.stopPropagation()}><header><button onClick={close}>‹ 返回</button><h2>存储空间</h2></header>{summary&&<div className="storage-status"><p>素材：{summary.assetCount}</p><p>图片：{summary.imageCount}</p><p>占用：{(summary.imageBytes/1024/1024).toFixed(1)} MB</p><button onClick={()=>void clean()}>清理无引用图片（{summary.orphanCount}）</button></div>}</div></div> }
function TagSheet({assets,close,filter}:{assets:AssetListItem[];close:()=>void;filter:(tag:Tag)=>void}) { const tags=[...new Map(assets.flatMap(asset=>asset.tags).map(tag=>[tag.id,tag])).values()]; return <div className="overlay" onClick={close}><div className="detail-sheet tag-sheet" onClick={event=>event.stopPropagation()}><header><button onClick={close}>‹ 返回</button><h2>标签管理</h2></header>{tags.map(tag=><button className="tag-row" key={tag.id} onClick={()=>filter(tag)}>#{tag.name}<span>{assets.filter(asset=>asset.tags.some(t=>t.id===tag.id)).length} ›</span></button>)}</div></div> }
function Nav({tab,go}:{tab:Tab;go:(t:Tab)=>void}) { return <nav>{([{key:'home',icon:'⌂',label:'首页'},{key:'browse',icon:'▦',label:'分类'},{key:'favorites',icon:'♡',label:'收藏'},{key:'mine',icon:'◉',label:'我的'}]as const).map(x=><button key={x.key} className={tab===x.key?'selected':''} onClick={()=>go(x.key)}><i>{x.icon}</i><span>{x.label}</span></button>)}</nav> }
